### ISSUE TITLE
When Data Science Destabilizes Democracy and Facilitates Genocide

### ISSUE THREAD

**Issue by bensoltoff** [UC-MACSS/persp-analysis#371]
An interesting article I came across today - [When Data Science Destabilizes Democracy and Facilitates Genocide](http://www.fast.ai/2017/11/02/ethics/?utm_campaign=Data%2BPrism&utm_medium=web&utm_source=Data_Prism_5)

Not assigned reading, but particularly relevant given our topic this week in class.

**Comment by tamos** [comment]
Very interesting - thanks for sharing!

When I was living in Bangladesh, I had the opportunity to learn a bit about the situation of the Rohinyga people, and it is great to see this issue discussed outside of the humanitarian/human rights community. It is so important to understand the context around tech/data science - and I'm glad the author made that point. 

But I feel like the author is also being quite 'acontextual'. Pretty ironic, no? The Rohinyga have been persecuted and mistreated in Myanmar and in Chittagong, Bangladesh, since the 1960's. If fear and division wasn't spreading by Facebook it would be by blogs, if it wasn't blogs it would be by text messages, it it wasn't text messages it would be plain old gossip.

**Comment by bensoltoff** [comment]
> I wonder if the more helpful point would have been to focus on creating solutions - i.e., social networks that subtly encourage cross-cultural understanding.

Would be helpful, not just in this more severe context but even in the US. Think about how Facebook and social media companies have contributed to increasing polarization of news consumption and ideology. The problem is that until now these companies have not been held to any higher ethical standard beyond profit maximization and minimal government regulation. Google may have once claimed ["don't be evil](https://en.wikipedia.org/wiki/Don%27t_be_evil) as its corporate motto and guiding philosophy - it's not as clear that they still follow it in practice.
