### ISSUE TITLE
Does Adam Bonica et al's Field Experiment Have a Pre-Registration Record?

### ISSUE THREAD

**Issue by xiuyuanzhang** [UC-MACSS/persp-analysis#374]
I've been trying to find some information from the source (aka the researchers themselves on their design and operationalized constructs) but can't find anything. Aren't they supposed to pre-register their study and make that public even if no paper come out the study?

**Comment by bensoltoff** [comment]
No, federal law and IRB regulations do not require pre-registration of an experimental protocol with a third-party. Generally the research would need to be approved by the IRB at the university where the researcher is employed, but otherwise there is no mandate to register the experiment elsewhere. Some journals require pre-registration in order to publish the paper, but these are only a small minority of academic journals.

You might be able to obtain the original IRB proposal, though certainly not in time to submit the assignment on Monday.

**Comment by xiuyuanzhang** [comment]
Thank you!
